import { NextResponse } from 'next/server'
import PDFDocument from 'pdfkit'

interface ExportRequest {
  title?: string
  oneSentence: string
  keyFindings: string[]
  methodology: string
  conclusion: string
}

function buildPdfBuffer(data: ExportRequest): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc: any = new PDFDocument({
      size: 'A4',
      margin: 60,
      autoFirstPage: false,
      info: {
        Title: data.title || 'Paper Summary',
        Creator: 'Paper-Summarizer (summarizeai.app)',
      },
    })

    const chunks: Buffer[] = []
    doc.on('data', (chunk: Buffer) => chunks.push(Buffer.from(chunk)))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    // ── Page 1 ──
    doc.addPage()

    // Header bar
    const pageWidth = doc.page.width
    doc
      .fillColor('#1e3a5f')
      .rect(0, 0, pageWidth, 55)
      .fill()

    doc
      .fontSize(20)
      .font('Helvetica-Bold')
      .fillColor('#ffffff')
      .text('📄 Paper Summary', 60, 18)

    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#93c5fd')
      .text('Generated by Paper-Summarizer', pageWidth - 60, 22, {
        align: 'right',
      })

    // ── Title ──
    doc
      .moveDown(1.5)
      .fontSize(18)
      .font('Helvetica-Bold')
      .fillColor('#1e293b')
      .text(data.title || 'Research Paper Summary', { align: 'left' })

    // ── One-sentence summary ──
    doc
      .moveDown(1)
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor('#2563eb')
      .text('📌 Summary', { underline: true, undercolor: '#2563eb' })

    doc
      .moveDown(0.3)
      .fontSize(11)
      .font('Helvetica')
      .fillColor('#334155')
      .text(data.oneSentence, {
        align: 'left',
        indent: 10,
        continued: true,
      })

    // ── Key Findings ──
    doc
      .moveDown(1.2)
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor('#2563eb')
      .text('🔑 Key Findings', { underline: true, undercolor: '#2563eb' })

    doc
      .moveDown(0.3)
      .fontSize(11)
      .font('Helvetica')
      .fillColor('#334155')

    data.keyFindings.forEach((finding, index) => {
      const num = `${index + 1}.`
      doc.text(num, { column: 70, width: 20, align: 'right' })
      doc.text(finding, {
        column: 90,
        width: pageWidth - 110,
        align: 'left',
      })
      if (index < data.keyFindings.length - 1) {
        doc.moveDown(0.5)
      }
    })

    // ── Methodology ──
    doc
      .moveDown(1.2)
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor('#2563eb')
      .text('🔬 Methodology', { underline: true, undercolor: '#2563eb' })

    doc
      .moveDown(0.3)
      .fontSize(11)
      .font('Helvetica')
      .fillColor('#334155')
      .text(data.methodology, {
        align: 'left',
        indent: 10,
      })

    // ── Conclusion ──
    doc
      .moveDown(1.2)
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor('#2563eb')
      .text('💡 Conclusion', { underline: true, undercolor: '#2563eb' })

    doc
      .moveDown(0.3)
      .fontSize(11)
      .font('Helvetica')
      .fillColor('#334155')
      .text(data.conclusion, {
        align: 'left',
        indent: 10,
      })

    // ── Footer ──
    const footerY = doc.page.height - 30
    doc
      .fontSize(8)
      .font('Helvetica-Oblique')
      .fillColor('#94a3b8')
      .text('Generated by Paper-Summarizer (summarizeai.app)', {
        align: 'center',
        width: pageWidth,
      })

    doc.end()
  })
}

export async function POST(request: Request) {
  let body: ExportRequest
  try {
    body = await request.json()
  } catch {
    return NextResponse.json(
      { error: 'Invalid JSON body' },
      { status: 400 }
    )
  }

  // Validate required fields
  if (!body.oneSentence || !Array.isArray(body.keyFindings) || !body.methodology || !body.conclusion) {
    return NextResponse.json(
      { error: 'Missing required fields: oneSentence, keyFindings, methodology, conclusion' },
      { status: 400 }
    )
  }

  try {
    const pdfBuffer = await buildPdfBuffer(body)

    const filename = (body.title || 'paper-summary')
      .replace(/[^a-zA-Z0-9\u4e00-\u9fff\s-]/g, '')
      .replace(/\s+/g, '-')
      .toLowerCase()
      .slice(0, 80)

    return new NextResponse(pdfBuffer.buffer as ArrayBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}.pdf"`,
        'X-Content-Type-Options': 'nosniff',
      },
    })
  } catch (error) {
    console.error('PDF generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    )
  }
}
